//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.10.13 at 09:39:52 PM VET
//


package com.cloudator.restapp.forecastweather.service.dto;

import com.cloudator.restapp.forecastweather.utils.LocalDateTimeAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="location">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="altitude" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="geobase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="geobaseid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="meta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="lastupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="calctime" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="nextupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sun">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="rise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="set" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="forecast">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="time" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="symbol">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="precipitation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="windDirection">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="deg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="windSpeed">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="mps" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="temperature">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                     &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                     &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="pressure">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="humidity">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="clouds">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "location",
        "credit",
        "meta",
        "sun",
        "forecast"
})
@XmlRootElement(name = "weatherdata")
public class WeatherData {

    @XmlElement(required = true)
    protected WeatherData.Location location;
    @XmlElement(required = true)
    protected String credit;
    @XmlElement(required = true)
    protected WeatherData.Meta meta;
    @XmlElement(required = true)
    protected WeatherData.Sun sun;
    @XmlElement(required = true)
    protected WeatherData.Forecast forecast;

    /**
     * Gets the value of the location property.
     *
     * @return possible object is
     * {@link WeatherData.Location }
     */
    public WeatherData.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     *
     * @param value allowed object is
     *              {@link WeatherData.Location }
     */
    public void setLocation(WeatherData.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the credit property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * Gets the value of the meta property.
     *
     * @return possible object is
     * {@link WeatherData.Meta }
     */
    public WeatherData.Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     *
     * @param value allowed object is
     *              {@link WeatherData.Meta }
     */
    public void setMeta(WeatherData.Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the sun property.
     *
     * @return possible object is
     * {@link WeatherData.Sun }
     */
    public WeatherData.Sun getSun() {
        return sun;
    }

    /**
     * Sets the value of the sun property.
     *
     * @param value allowed object is
     *              {@link WeatherData.Sun }
     */
    public void setSun(WeatherData.Sun value) {
        this.sun = value;
    }

    /**
     * Gets the value of the forecast property.
     *
     * @return possible object is
     * {@link WeatherData.Forecast }
     */
    public WeatherData.Forecast getForecast() {
        return forecast;
    }

    /**
     * Sets the value of the forecast property.
     *
     * @param value allowed object is
     *              {@link WeatherData.Forecast }
     */
    public void setForecast(WeatherData.Forecast value) {
        this.forecast = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="time" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="symbol">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="precipitation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="windDirection">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="deg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="windSpeed">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="mps" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="temperature">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                           &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                           &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="pressure">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="humidity">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="clouds">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "time"
    })
    public static class Forecast {

        @XmlElement(required = true)
        protected List<WeatherData.Forecast.Time> time;

        /**
         * Gets the value of the time property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the time property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTime().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WeatherData.Forecast.Time }
         */
        public List<WeatherData.Forecast.Time> getTime() {
            if (time == null) {
                time = new ArrayList<WeatherData.Forecast.Time>();
            }
            return this.time;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="symbol">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="precipitation" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="windDirection">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="deg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="windSpeed">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="mps" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="temperature">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                 &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="pressure">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="humidity">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="clouds">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="to" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "symbol",
                "precipitation",
                "windDirection",
                "windSpeed",
                "temperature",
                "pressure",
                "humidity",
                "clouds"
        })
        public static class Time {

            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.Symbol symbol;
            @XmlElement(required = true)
            protected String precipitation;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.WindDirection windDirection;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.WindSpeed windSpeed;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.Temperature temperature;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.Pressure pressure;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.Humidity humidity;
            @XmlElement(required = true)
            protected WeatherData.Forecast.Time.Clouds clouds;
            @XmlAttribute(name = "from")
            @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
            @XmlSchemaType(name = "dateTime")
            protected LocalDateTime from;
            @XmlAttribute(name = "to")
            @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
            @XmlSchemaType(name = "dateTime")
            protected LocalDateTime to;

            /**
             * Gets the value of the symbol property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.Symbol }
             */
            public WeatherData.Forecast.Time.Symbol getSymbol() {
                return symbol;
            }

            /**
             * Sets the value of the symbol property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.Symbol }
             */
            public void setSymbol(WeatherData.Forecast.Time.Symbol value) {
                this.symbol = value;
            }

            /**
             * Gets the value of the precipitation property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getPrecipitation() {
                return precipitation;
            }

            /**
             * Sets the value of the precipitation property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setPrecipitation(String value) {
                this.precipitation = value;
            }

            /**
             * Gets the value of the windDirection property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.WindDirection }
             */
            public WeatherData.Forecast.Time.WindDirection getWindDirection() {
                return windDirection;
            }

            /**
             * Sets the value of the windDirection property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.WindDirection }
             */
            public void setWindDirection(WeatherData.Forecast.Time.WindDirection value) {
                this.windDirection = value;
            }

            /**
             * Gets the value of the windSpeed property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.WindSpeed }
             */
            public WeatherData.Forecast.Time.WindSpeed getWindSpeed() {
                return windSpeed;
            }

            /**
             * Sets the value of the windSpeed property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.WindSpeed }
             */
            public void setWindSpeed(WeatherData.Forecast.Time.WindSpeed value) {
                this.windSpeed = value;
            }

            /**
             * Gets the value of the temperature property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.Temperature }
             */
            public WeatherData.Forecast.Time.Temperature getTemperature() {
                return temperature;
            }

            /**
             * Sets the value of the temperature property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.Temperature }
             */
            public void setTemperature(WeatherData.Forecast.Time.Temperature value) {
                this.temperature = value;
            }

            /**
             * Gets the value of the pressure property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.Pressure }
             */
            public WeatherData.Forecast.Time.Pressure getPressure() {
                return pressure;
            }

            /**
             * Sets the value of the pressure property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.Pressure }
             */
            public void setPressure(WeatherData.Forecast.Time.Pressure value) {
                this.pressure = value;
            }

            /**
             * Gets the value of the humidity property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.Humidity }
             */
            public WeatherData.Forecast.Time.Humidity getHumidity() {
                return humidity;
            }

            /**
             * Sets the value of the humidity property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.Humidity }
             */
            public void setHumidity(WeatherData.Forecast.Time.Humidity value) {
                this.humidity = value;
            }

            /**
             * Gets the value of the clouds property.
             *
             * @return possible object is
             * {@link WeatherData.Forecast.Time.Clouds }
             */
            public WeatherData.Forecast.Time.Clouds getClouds() {
                return clouds;
            }

            /**
             * Sets the value of the clouds property.
             *
             * @param value allowed object is
             *              {@link WeatherData.Forecast.Time.Clouds }
             */
            public void setClouds(WeatherData.Forecast.Time.Clouds value) {
                this.clouds = value;
            }

            /**
             * Gets the value of the from property.
             *
             * @return possible object is
             * {@link String }
             */
            public LocalDateTime getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setFrom(LocalDateTime value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             *
             * @return possible object is
             * {@link String }
             */
            public LocalDateTime getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setTo(LocalDateTime value) {
                this.to = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="all" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Clouds {

                @XmlAttribute(name = "value")
                protected String value;
                @XmlAttribute(name = "all")
                protected Integer all;
                @XmlAttribute(name = "unit")
                protected String unit;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the all property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getAll() {
                    return all;
                }

                /**
                 * Sets the value of the all property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setAll(Integer value) {
                    this.all = value;
                }

                /**
                 * Gets the value of the unit property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Humidity {

                @XmlAttribute(name = "value")
                protected Integer value;
                @XmlAttribute(name = "unit")
                protected String unit;

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setValue(Integer value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the unit property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Pressure {

                @XmlAttribute(name = "unit")
                protected String unit;
                @XmlAttribute(name = "value")
                protected BigDecimal value;

                /**
                 * Gets the value of the unit property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setValue(BigDecimal value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="var" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Symbol {

                @XmlAttribute(name = "number")
                protected Integer number;
                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "var")
                protected String var;

                /**
                 * Gets the value of the number property.
                 *
                 * @return possible object is
                 * {@link Integer }
                 */
                public Integer getNumber() {
                    return number;
                }

                /**
                 * Sets the value of the number property.
                 *
                 * @param value allowed object is
                 *              {@link Integer }
                 */
                public void setNumber(Integer value) {
                    this.number = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the var property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getVar() {
                    return var;
                }

                /**
                 * Sets the value of the var property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setVar(String value) {
                    this.var = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Temperature {

                @XmlAttribute(name = "unit")
                protected String unit;
                @XmlAttribute(name = "value")
                protected BigDecimal value;
                @XmlAttribute(name = "min")
                protected BigDecimal min;
                @XmlAttribute(name = "max")
                protected BigDecimal max;

                /**
                 * Gets the value of the unit property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setValue(BigDecimal value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the min property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getMin() {
                    return min;
                }

                /**
                 * Sets the value of the min property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setMin(BigDecimal value) {
                    this.min = value;
                }

                /**
                 * Gets the value of the max property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getMax() {
                    return max;
                }

                /**
                 * Sets the value of the max property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setMax(BigDecimal value) {
                    this.max = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="deg" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class WindDirection {

                @XmlAttribute(name = "deg")
                protected BigDecimal deg;
                @XmlAttribute(name = "code")
                protected String code;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the deg property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getDeg() {
                    return deg;
                }

                /**
                 * Sets the value of the deg property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setDeg(BigDecimal value) {
                    this.deg = value;
                }

                /**
                 * Gets the value of the code property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getCode() {
                    return code;
                }

                /**
                 * Sets the value of the code property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setCode(String value) {
                    this.code = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="mps" type="{http://www.w3.org/2001/XMLSchema}decimal" />
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class WindSpeed {

                @XmlAttribute(name = "mps")
                protected BigDecimal mps;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the mps property.
                 *
                 * @return possible object is
                 * {@link BigDecimal }
                 */
                public BigDecimal getMps() {
                    return mps;
                }

                /**
                 * Sets the value of the mps property.
                 *
                 * @param value allowed object is
                 *              {@link BigDecimal }
                 */
                public void setMps(BigDecimal value) {
                    this.mps = value;
                }

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is
                 * {@link String }
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is
                 *              {@link String }
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="timezone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="location">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="altitude" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
     *                 &lt;attribute name="geobase" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="geobaseid" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "name",
            "type",
            "country",
            "timezone",
            "location"
    })
    public static class Location {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected String country;
        @XmlElement(required = true)
        protected String timezone;
        @XmlElement(required = true)
        protected WeatherData.Location.InnerLocation location;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the type property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the country property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the timezone property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getTimezone() {
            return timezone;
        }

        /**
         * Sets the value of the timezone property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTimezone(String value) {
            this.timezone = value;
        }

        /**
         * Gets the value of the location property.
         *
         * @return possible object is
         * {@link WeatherData.Location.Location }
         */
        public WeatherData.Location.InnerLocation getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         *
         * @param value allowed object is
         *              {@link WeatherData.Location.Location }
         */
        public void setLocation(WeatherData.Location.InnerLocation value) {
            this.location = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="altitude" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" />
         *       &lt;attribute name="geobase" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="geobaseid" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InnerLocation {

            @XmlAttribute(name = "altitude")
            protected Integer altitude;
            @XmlAttribute(name = "latitude")
            protected BigDecimal latitude;
            @XmlAttribute(name = "longitude")
            protected BigDecimal longitude;
            @XmlAttribute(name = "geobase")
            protected String geobase;
            @XmlAttribute(name = "geobaseid")
            protected Integer geobaseid;

            /**
             * Gets the value of the altitude property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getAltitude() {
                return altitude;
            }

            /**
             * Sets the value of the altitude property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setAltitude(Integer value) {
                this.altitude = value;
            }

            /**
             * Gets the value of the latitude property.
             *
             * @return possible object is
             * {@link BigDecimal }
             */
            public BigDecimal getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setLatitude(BigDecimal value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             *
             * @return possible object is
             * {@link BigDecimal }
             */
            public BigDecimal getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             *
             * @param value allowed object is
             *              {@link BigDecimal }
             */
            public void setLongitude(BigDecimal value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the geobase property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getGeobase() {
                return geobase;
            }

            /**
             * Sets the value of the geobase property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setGeobase(String value) {
                this.geobase = value;
            }

            /**
             * Gets the value of the geobaseid property.
             *
             * @return possible object is
             * {@link Integer }
             */
            public Integer getGeobaseid() {
                return geobaseid;
            }

            /**
             * Sets the value of the geobaseid property.
             *
             * @param value allowed object is
             *              {@link Integer }
             */
            public void setGeobaseid(Integer value) {
                this.geobaseid = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="lastupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="calctime" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="nextupdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "lastupdate",
            "calctime",
            "nextupdate"
    })
    public static class Meta {

        @XmlElement(required = true)
        protected String lastupdate;
        @XmlElement(required = true)
        protected BigDecimal calctime;
        @XmlElement(required = true)
        protected String nextupdate;

        /**
         * Gets the value of the lastupdate property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLastupdate() {
            return lastupdate;
        }

        /**
         * Sets the value of the lastupdate property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLastupdate(String value) {
            this.lastupdate = value;
        }

        /**
         * Gets the value of the calctime property.
         *
         * @return possible object is
         * {@link BigDecimal }
         */
        public BigDecimal getCalctime() {
            return calctime;
        }

        /**
         * Sets the value of the calctime property.
         *
         * @param value allowed object is
         *              {@link BigDecimal }
         */
        public void setCalctime(BigDecimal value) {
            this.calctime = value;
        }

        /**
         * Gets the value of the nextupdate property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getNextupdate() {
            return nextupdate;
        }

        /**
         * Sets the value of the nextupdate property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setNextupdate(String value) {
            this.nextupdate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="rise" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="set" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Sun {

        @XmlAttribute(name = "rise")
        @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected LocalDateTime rise;
        @XmlAttribute(name = "set")
        @XmlJavaTypeAdapter(LocalDateTimeAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected LocalDateTime set;

        /**
         * Gets the value of the rise property.
         *
         * @return possible object is
         * {@link String }
         */
        public LocalDateTime getRise() {
            return rise;
        }

        /**
         * Sets the value of the rise property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setRise(LocalDateTime value) {
            this.rise = value;
        }

        /**
         * Gets the value of the set property.
         *
         * @return possible object is
         * {@link String }
         */
        public LocalDateTime getSet() {
            return set;
        }

        /**
         * Sets the value of the set property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setSet(LocalDateTime value) {
            this.set = value;
        }

    }

}
